// Generated by Funtester with Selenium plugin.

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;
import org.testng.annotations.Test;

public class ${test.name} extends ActivityInstrumentationTestCase2< MainActivity > {

	private WebDriver driver;
	private Actions action;
	
	public ${test.name}() {
	    super( MainActivity.class );
	}
	
	@Override
	protected void setUp() throws Exception {
		//Setup driver
		this.driver = new FirefoxDriver();
		driver.get("site.com");
		//Setup extended actions
		this.action = new Actions( this.driver );
		<#list test.setUpOnceCommands as cmd>
		${cmd}
		</#list>
	}

	@Override
	protected void tearDown() throws Exception {
		this.driver.close();
		this.driver.quit();
	}
	
	//Test methods:
	<#list test.methods as method>
	public void test_${method.name}() {
		<#list method.commands as cmd>
		${cmd};
		</#list>
	}
	
	</#list>
	
}