// Generated by FunTester

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.*;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.testng.*;

/**
 * My Test Case
 */
@Test ( groups={
  "functional"
  , "slow"
  , "bla"
} )
public class TestGerado {

	private WebDriver driver;
	private Actions action;
	
	//
	// HELPER METHODS
	//
	
	public void clickSelenium(WebElement element) {
		element.click();
	}
	
	public void sendKeysSelenium(WebElement element, String value) {
		element.sendKeys( value );
	}
	
	public void selectByVisibleTextSelenium(Select element, String value) {
		element.selectByVisibleText( value );
	}
	
	public void selectFirstSelenium(Select element) {
		element.selectByIndex( 0 );
	}
	
	public void doubleClickSelenium(WebElement element) {
		action.doubleClick( element ).perform();
	}
	
	public void dragAndDropSelenium(WebElement elementDrag, WebElement elementDrop) {
		action.dragAndDrop( elementDrag, elementDrop ).perform();
	}
	
	//
	// SETUP AND TEAR DOWN
	//
	
	@BeforeMethod
	public void setUp() {
		this.driver = new FirefoxDriver();
		driver.get( "site.com" );
		this.action = new Actions( this.driver );
	}
	
	@AfterMethod
	public void tearDown() {
		this.driver.close();
		this.driver.quit();
	}
	
	//
	// TESTS
	//
	
	@Test
	public void all_field_values_at_the_lower_limit() {
		dragAndDropSelenium( driver.findElement( By.id( "MainFrame" ) ),driver.findElement( By.id( "MainFrame" ) ) );
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"_0xd4_ j0 9X7N456 _-D  _.77 .._N" );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Desktop Applications Vocabulary (English)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//Action [ close ] can't be translated
	}
	
	@Test
	public void all_field_values_just_above_lower_limit() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"- -o._- e -3-_r5-c_-" );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Vocabulário para Aplicações Desktop (Portuguese)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//Action [ close ] can't be translated
	}
	
	@Test
	public void all_field_values_at_the_upper_limit() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"me --.2__..D AS3" );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Vocabulário para Aplicações Desktop (Portuguese)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//Action [ close ] can't be translated
	}
	
	@Test
	public void all_field_values_just_below_upper_limit() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) )," _3F" );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Desktop Applications Vocabulary (English)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//Action [ close ] can't be translated
	}
	
	@Test
	public void all_field_values_with_the_median() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"XR." );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Vocabulário para Aplicações Desktop (Portuguese)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//Action [ close ] can't be translated
	}
	
	@Test
	public void all_field_values_with_zero_or_equivalent() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"I_--G " );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Desktop Applications Vocabulary (English)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//Action [ close ] can't be translated
	}
	
	@Test
	public void all_fields_with_random_values() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"15X_7GT m " );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Desktop Applications Vocabulary (English)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//Action [ close ] can't be translated
	}
	
	@Test
	public void just_the_required_fields_with_random_values() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"_ktX -2R" );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Vocabulário para Aplicações Desktop (Portuguese)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//Action [ close ] can't be translated
	}
	
	@Test
	public void name_just_below_lower_limit() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"" );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Vocabulário para Aplicações Desktop (Portuguese)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//Action [ close ] can't be translated
	}
	
	@Test
	public void vocabulary_just_below_lower_limit() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"W-F ._F_.84g 6-_t_6. . " );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"BNd{:H{Jc:|K6||6SW/3" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//check
		//Action [ close ] can't be translated
	}
	
	@Test
	public void name_with_random_value_below_lower_limit() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"" );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Desktop Applications Vocabulary (English)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//Action [ close ] can't be translated
	}
	
	@Test
	public void vocabulary_with_random_value_below_lower_limit() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"D_6_ Xo  5 T 0_26Og _" );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"N7sp*-GB#N<7)N.V|1uZ5hXP]u`" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//check
		//Action [ close ] can't be translated
	}
	
	@Test
	public void name_just_above_upper_limit() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"" );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Vocabulário para Aplicações Desktop (Portuguese)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//Action [ close ] can't be translated
	}
	
	@Test
	public void vocabulary_just_above_upper_limit() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"-43  --." );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"{xe[(}rM9qn{SF$8T@=_@9qM_HuzkCt" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//check
		//Action [ close ] can't be translated
	}
	
	@Test
	public void name_with_random_value_above_upper_limit() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"" );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Vocabulário para Aplicações Desktop (Portuguese)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//Action [ close ] can't be translated
	}
	
	@Test
	public void vocabulary_with_random_value_above_upper_limit() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"c.8  S L" );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"qnb>=t9uYiE" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//check
		//Action [ close ] can't be translated
	}
	
	@Test
	public void all_the_required_fields_except_name() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Desktop Applications Vocabulary (English)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//check
		//Action [ close ] can't be translated
	}
	
	@Test
	public void all_the_required_fields_except_vocabulary() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),".8__14." );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//check
		//Action [ close ] can't be translated
	}
	
	@Test
	public void name_with_invalid_format() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"J$Am}lRN4j.Ny#tqS;wml:-&Va_Z0f!&#@>);j,.&j~Az,8J+mfzUEWn~FPqW[wc1uVJb&N3W|=F?`&UM)e<?-?9" );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"Desktop Applications Vocabulary (English)" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//check
		//Action [ close ] can't be translated
	}
	
	@Test
	public void vocabulary_with_invalid_format() {
		//Action [ show ] can't be translated
		clickSelenium( driver.findElement( By.id( "fileMenu" ) ) );
		clickSelenium( driver.findElement( By.id( "newMenu" ) ) );
		//Action [ show ] can't be translated
		sendKeysSelenium( driver.findElement( By.id( "name" ) ),"3" );
		selectByVisibleTextSelenium( ( new Select ( driver.findElement( By.id( "vocabulary" ) ) ) ),"" );
		clickSelenium( driver.findElement( By.id( "okButton" ) ) );
		//Action [ close ] can't be translated
	}
	
}